name: T# CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make install
      run: sudo make install
    - name: prepare
      run: git clone https://github.com/ibukiyoshidaa/Tsharp; mv Tsharp/sample/main.t# sample.t#
    - name: run
      run: t# sample.t#
    - name: clean
      run: sudo make clean; rm -rf sample.t# Tsharp
