name: T# CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make install
      run: sudo make install
    - name: run
      run: t# sample/main.t#
    - name: clean
      run: sudo make clean;
